# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3 --cleanup=whitespace`
# and put the release notes into the commit message for the tag.
# The `--cleanup` flag avoids markdown headings being stripped as comments.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  tests:
    # Do only release when CI succeeds.
    uses: ./.github/workflows/workflow.yaml

  release:
    # Do only release when CI succeeds.
    needs: [test-nixpkgs, test-examples]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare release notes and artifacts
        run: .github/workflows/release_prep.sh ${{ env.GITHUB_REF_NAME }} > release_notes.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          fail_on_unmatched_files: true
          files: rules_nixpkgs*-*.tar.gz
